# Mounting Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [0]:
df = pd.read_excel('/content/drive/My Drive/Sabnis sir project/Covid_classification_project_dataset.xlsx')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4626 entries, 0 to 4625
Data columns (total 30 columns):
 #   Column                                           Non-Null Count  Dtype         
---  ------                                           --------------  -----         
 0   Sr No                                            4626 non-null   int64         
 1   Hospital Code                                    4626 non-null   object        
 2   Case No.                                         4625 non-null   object        
 3   Age                                              4600 non-null   float64       
 4   Gender                                           4624 non-null   object        
 5   Ward                                             4623 non-null   object        
 6   Occupation                                       348 non-null    object        
 7   District                                         4626 non-null   object        
 8   State                                 

## Dropping irrelevant columns

In [0]:
df=df.drop(['Sr No', 'Hospital Code','Case No.','Occupation','District', 'State','Ward',
            'Sample collected (Yes/No)','Date of arrival in India','Flight No','Seat No',
            'Date of onset of symptoms','Date of sample collection','Remarks','Sample collection centre',
            'Sample tested at','Lab that confirmed the result',
            'Date of Reporting','Date of Isolation','Date of outcome'],axis=1)  

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4626 entries, 0 to 4625
Data columns (total 10 columns):
 #   Column                                           Non-Null Count  Dtype  
---  ------                                           --------------  -----  
 0   Age                                              4600 non-null   float64
 1   Gender                                           4624 non-null   object 
 2   Travel to COVID afftected country (Yes/No)       134 non-null    object 
 3   Contact with COVID19 case (Yes/No)               690 non-null    object 
 4   Symptoms at admission                            3720 non-null   object 
 5   Underlying medical condition                     327 non-null    object 
 6   Current Clinical Status                          4461 non-null   object 
 7   Outcome (Discharged/Death/Admitted)              4623 non-null   object 
 8   Is patient member of cluster of COVID19(Yes/No)  722 non-null    object 
 9   Total Contacts                

## Filling Missing Age Values

In [9]:
df['Age'].mean()

37.79836956521739

In [0]:
df['Age'].fillna(38,inplace=True)

## Cleaning 'Underlying medical condition'

In [11]:
df['Underlying medical condition'].value_counts(dropna=False)

NaN                                       4299
No                                          74
DM,Hypertension                             50
Hypertension                                40
None                                        35
NO                                          28
DM                                          19
Yes                                          9
ANC                                          7
Stable                                       5
IHD                                          5
COPD                                         4
Asthma                                       4
Hypertension,IHD                             4
Hypertension,Hypothyroidism                  2
DM,Hypertension,IHD                          2
Alcoholic_liver_disease                      2
Hypothyroidism                               2
DM,Asthma                                    2
Hypertension,Chronic_renal_disease           2
DM,CKD                                       2
Obesity      

In [0]:
df = df.fillna({'Underlying medical condition':'No'})
df = df.replace({'Underlying medical condition':['None','NO','no','Stable']},'No')
df = df.replace({'Underlying medical condition':['None','NO']},'No')

In [0]:
# Making different columns for each condition
col=df['Underlying medical condition']

for i in col:
    x=[]
    k=i.split(',')
    for j in k:
        x.append(j.strip())
    
    conditions=['No','DM','Hypertension','Yes','ANC','IHD','COPD','Asthama','Hypothyroidism',
               'Chronic_renal_disease','Obesity','CKD','Alcoholic_liver_disease','Tobaco_chewer',
               'Thyroid_disorder','HepatitisB','HIV','Hemiparesis','Bronchitis','Chronic_kidney_disease',
               'Alcoholic','Renal_stone','Breathlessness']
    
    for ele in conditions:
  
        if ele in x:

      
            df[ele]=1
        
        else:
            df[ele]=0

In [14]:
col=df['Underlying medical condition']
t=0
for i in col:
    x=[]
    k=i.split(',')
    for j in k:
        x.append(j.strip())
    
    conditions=['No','DM','Hypertension','Yes','ANC','IHD','COPD','Asthama','Hypothyroidism',
               'Chronic_renal_disease','Obesity','CKD','Alcoholic_liver_disease','Tobaco_chewer',
               'Thyroid_disorder','HepatitisB','HIV','Hemiparesis','Bronchitis','Chronic_kidney_disease',
               'Alcoholic','Renal_stone','Breathlessness']
    for ele in conditions:
  
        if ele in x:

      
            df[ele][t]=1
        
        else:
            df[ele][t]=0
    t=t+1
    

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [0]:
df = df.drop(['Underlying medical condition'],axis=1)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4626 entries, 0 to 4625
Data columns (total 32 columns):
 #   Column                                           Non-Null Count  Dtype  
---  ------                                           --------------  -----  
 0   Age                                              4626 non-null   float64
 1   Gender                                           4624 non-null   object 
 2   Travel to COVID afftected country (Yes/No)       134 non-null    object 
 3   Contact with COVID19 case (Yes/No)               690 non-null    object 
 4   Symptoms at admission                            3720 non-null   object 
 5   Current Clinical Status                          4461 non-null   object 
 6   Outcome (Discharged/Death/Admitted)              4623 non-null   object 
 7   Is patient member of cluster of COVID19(Yes/No)  722 non-null    object 
 8   Total Contacts                                   3113 non-null   float64
 9   No                            

## Cleaning 'Current Clinical Status' Column

In [17]:
df['Current Clinical Status'].value_counts(dropna=False)

Stable                            3948
Admitted                           392
NaN                                165
Death                               54
Asymptomatic                        28
DEATH                                9
death                                6
Critical                             3
on oxygen                            3
UnStable                             3
PATIENT ON BIPAP                     2
criticl on ventilater                2
Roudy                                1
CRITICAL                             1
In ICU                               1
EXPIRED ON03/05/2020.(2.00 AM)       1
NIV                                  1
Intubated                            1
Critical on o2                       1
UnStable on NIV                      1
Critical on ventilator               1
On Oxygen Support                    1
OnO2ICU                              1
Name: Current Clinical Status, dtype: int64

In [18]:
df = df.fillna({'Current Clinical Status':'Admitted'})
df = df.replace({'Current Clinical Status':['Admited','ADMITED','Admitted (7A)']},'Admitted')
df = df.replace({'Current Clinical Status':['DEATH','death','EXPIRED ON03/05/2020.(2.00 AM)']},'Death')
df = df.replace({'Current Clinical Status':['Asymptomatic','Unstable','criticl on ventilater','PATIENT ON BIPAP','INTUBATED','CRITICAL',
                                            'UnStable','Critical on ventilator','In ICU','Roudy','UnStable on NIV','Critical on o2','Intubated',
                                            ]},'Critical')
df = df.replace({'Current Clinical Status':['NIV','on oxygen','On Oxygen Support','OnO2ICU']},'Stable')
df['Current Clinical Status'].value_counts(dropna=False)

Stable      3954
Admitted     557
Death         70
Critical      45
Name: Current Clinical Status, dtype: int64

## Cleaning 'Travel to COVID affected country' column

In [19]:
df = df.fillna({'Travel to COVID afftected country (Yes/No)':'No'})
df = df.replace({'Travel to COVID afftected country (Yes/No)':['NO']},'No')
df['Travel to COVID afftected country (Yes/No)'].value_counts(dropna=False)

No     4613
Yes      13
Name: Travel to COVID afftected country (Yes/No), dtype: int64

## Cleaning 'Contacts with COVID case' column

In [20]:
df['Contact with COVID19 case (Yes/No)'].value_counts(dropna=False)

NaN             3936
NO               354
No               161
Yes              107
Stable            60
Asymptomatic       3
Yes                3
no                 1
Hospitalies        1
Name: Contact with COVID19 case (Yes/No), dtype: int64

In [21]:
df = df.fillna({'Contact with COVID19 case (Yes/No)':'No'})
df = df.replace({'Contact with COVID19 case (Yes/No)':['NO','no']},'No')
df = df.replace({'Contact with COVID19 case (Yes/No)':['STABLE','Stable','yes','YES','Yes ','Asymptomatic','Hospitalies']},'Yes')
df['Contact with COVID19 case (Yes/No)'].value_counts()

No     4452
Yes     174
Name: Contact with COVID19 case (Yes/No), dtype: int64

## Cleaning 'Is patitent member of cluster COVID' column

In [22]:
df['Is patient member of cluster of COVID19(Yes/No)'].value_counts(dropna=False)

NaN    3904
NO      523
Yes     112
No       85
no        2
Name: Is patient member of cluster of COVID19(Yes/No), dtype: int64

In [23]:
df = df.replace({'Is patient member of cluster of COVID19(Yes/No)':['NO','no']},'No')
df = df.replace({'Is patient member of cluster of COVID19(Yes/No)':['YES','yes']},'Yes')
df = df.fillna({'Is patient member of cluster of COVID19(Yes/No)':'No'})
df['Is patient member of cluster of COVID19(Yes/No)'].value_counts(dropna=False)

No     4514
Yes     112
Name: Is patient member of cluster of COVID19(Yes/No), dtype: int64

##  Filling 'Total contacts' column

In [24]:
df['Total Contacts'].value_counts(dropna=False)

0.0     1547
NaN     1513
3.0      206
4.0      183
5.0      182
6.0      134
2.0      119
7.0      114
8.0       91
1.0       75
9.0       69
10.0      62
11.0      49
12.0      46
13.0      41
14.0      40
16.0      23
15.0      22
22.0      18
18.0      15
17.0      11
34.0      10
21.0       9
19.0       7
25.0       6
27.0       6
29.0       6
24.0       4
28.0       3
23.0       2
36.0       2
30.0       2
31.0       1
20.0       1
64.0       1
40.0       1
48.0       1
39.0       1
35.0       1
37.0       1
45.0       1
Name: Total Contacts, dtype: int64

In [0]:
df = df.fillna({'Total Contacts':0})

## Cleaning 'Symptoms' column


In [26]:
df['Symptoms at admission '].value_counts(dropna=False)

Fever,Cough                                2268
NaN                                         906
Cough,Cold,Fever                            815
Asymptomatic                                184
Breathlessness                               59
                                           ... 
Fever,Headache                                1
Diarrhoea,Nausea                              1
Breathlessness,Bodyache                       1
Fever,Cough,Cold,Bodyache,Loose motion        1
Breathlessness,Loss of appetite,Fatigue       1
Name: Symptoms at admission , Length: 154, dtype: int64

In [27]:
df['Symptoms at admission '].fillna('Fever',inplace=True)
df['Symptoms at admission '].isnull().sum()

0

In [0]:
#Making different columns for each symptom


col=df['Symptoms at admission ']

for i in col:
    x=[]
    k=i.split(',')
    for j in k:
        x.append(j.strip())
    
    symptoms=['Fever','Cold','Cough','Breathlessness','Weakness','Vomiting','Sore Throat','Chest pain','Loss of appetite','Nausea','Abdominal pain','Loose motion','Diarrhoea']
    
    for ele in symptoms:
  
        if ele in x:

      
            df[ele]=1
        
        else:
            df[ele]=0
    
    

In [29]:
#Making different columns for each symptom


col=df['Symptoms at admission ']
t=0
for i in col:
    x=[]
    k=i.split(',')
    for j in k:
        x.append(j.strip())
    
    symptoms=['Fever','Cold','Cough','Breathlessness','Weakness','Vomiting','Sore Throat','Chest pain','Loss of appetite','Nausea','Abdominal pain','Loose motion','Diarrhoea']
    
    for ele in symptoms:
  
        if ele in x:

      
            df[ele][t]=1
        
        else:
            df[ele][t]=0
    t=t+1
    

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [0]:
df = df.drop(['Symptoms at admission '],axis=1)

## Cleaning 'Outcome' column

In [31]:
df['Outcome (Discharged/Death/Admitted)'].value_counts()

Admitted      2558
Discharged    1599
Death          194
DIscharged     135
discharged     122
dIscharged       6
death            5
DEATH            4
Name: Outcome (Discharged/Death/Admitted), dtype: int64

In [32]:
df = df.replace({'Outcome (Discharged/Death/Admitted)':['ADMITTED','Admitted ']},'Admitted')
df = df.replace({'Outcome (Discharged/Death/Admitted)':['DIscharged','discharged','dIscharged']},'Discharged')
df = df.replace({'Outcome (Discharged/Death/Admitted)':['death','DEATH']},'Death')
df['Outcome (Discharged/Death/Admitted)'].value_counts()

Admitted      2558
Discharged    1862
Death          203
Name: Outcome (Discharged/Death/Admitted), dtype: int64

In [33]:
df['Outcome']=df['Outcome (Discharged/Death/Admitted)']
df=df.drop('Outcome (Discharged/Death/Admitted)',axis=1)
df=df[(df.Outcome=='Discharged')|(df.Outcome=='Death')]
df.head()

Age Gender  ... Diarrhoea     Outcome
0  51.0      M  ...         0  Discharged
1  43.0      F  ...         0  Discharged
2  23.0      F  ...         0  Discharged
3  43.0      M  ...         0  Discharged
4  27.0      M  ...         0  Discharged

[5 rows x 43 columns]

In [34]:
df['Outcome'].value_counts(dropna =False)

Discharged    1862
Death          203
Name: Outcome, dtype: int64

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2065 entries, 0 to 4622
Data columns (total 43 columns):
 #   Column                                           Non-Null Count  Dtype  
---  ------                                           --------------  -----  
 0   Age                                              2065 non-null   float64
 1   Gender                                           2065 non-null   object 
 2   Travel to COVID afftected country (Yes/No)       2065 non-null   object 
 3   Contact with COVID19 case (Yes/No)               2065 non-null   object 
 4   Current Clinical Status                          2065 non-null   object 
 5   Is patient member of cluster of COVID19(Yes/No)  2065 non-null   object 
 6   Total Contacts                                   2065 non-null   float64
 7   No                                               2065 non-null   int64  
 8   DM                                               2065 non-null   int64  
 9   Hypertension                  

In [36]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2065 entries, 0 to 4622
Data columns (total 43 columns):
 #   Column                                           Non-Null Count  Dtype  
---  ------                                           --------------  -----  
 0   Age                                              2065 non-null   float64
 1   Gender                                           2065 non-null   object 
 2   Travel to COVID afftected country (Yes/No)       2065 non-null   object 
 3   Contact with COVID19 case (Yes/No)               2065 non-null   object 
 4   Current Clinical Status                          2065 non-null   object 
 5   Is patient member of cluster of COVID19(Yes/No)  2065 non-null   object 
 6   Total Contacts                                   2065 non-null   float64
 7   No                                               2065 non-null   int64  
 8   DM                                               2065 non-null   int64  
 9   Hypertension                  

## Splitting and transforming the dataset

In [0]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2,3,4,5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [39]:
print(X)

[[0.0 1.0 0.0 ... 0 0 0]
 [1.0 0.0 0.0 ... 0 0 0]
 [1.0 0.0 0.0 ... 0 0 0]
 ...
 [0.0 1.0 0.0 ... 0 0 0]
 [0.0 1.0 0.0 ... 0 0 0]
 [1.0 0.0 0.0 ... 0 0 0]]


In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 1 1 ... 0 0 0]


## Splitting data into Training and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Logistic Regression


In [42]:
from sklearn.linear_model import LogisticRegression
classifier_log = LogisticRegression(random_state = 0)
classifier_log.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [43]:
y_pred_log = classifier_log.predict(X_test)
print(np.concatenate((y_pred_log.reshape(len(y_pred_log),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_log = confusion_matrix(y_test, y_pred_log)
print(cm_log)
accuracy_score(y_test, y_pred_log)

[[ 29  26]
 [  4 458]]


0.941972920696325

# KNN CLassifier

In [45]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [46]:
y_pred_knn = classifier_knn.predict(X_test)
print(np.concatenate((y_pred_knn.reshape(len(y_pred_knn),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [0 1]]


In [47]:
cm_knn = confusion_matrix(y_test, y_pred_knn)
print(cm_knn)
accuracy_score(y_test, y_pred_knn)

[[ 11  44]
 [ 13 449]]


0.8897485493230174

# Support vector Classifier


In [48]:
from sklearn.svm import SVC
classifier_svc = SVC(kernel = 'linear', random_state = 0)
classifier_svc.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [49]:
y_pred_svc = classifier_svc.predict(X_test)
print(np.concatenate((y_pred_svc.reshape(len(y_pred_svc),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [50]:
cm_svc = confusion_matrix(y_test, y_pred_svc)
print(cm_svc)
accuracy_score(y_test, y_pred_svc)

[[ 26  29]
 [  5 457]]


0.9342359767891683

# Support Vector 'rbf' Classifier

In [51]:
from sklearn.svm import SVC
classifier_svcrbf = SVC(kernel = 'rbf', random_state = 1)
classifier_svcrbf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

In [52]:
y_pred_svcrbf = classifier_svcrbf.predict(X_test)
print(np.concatenate((y_pred_svcrbf.reshape(len(y_pred_svcrbf),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [53]:
cm_svcrbf = confusion_matrix(y_test, y_pred_svcrbf)
print(cm_svcrbf)
accuracy_score(y_test, y_pred_svcrbf)

[[  0  55]
 [  0 462]]


0.8936170212765957

# Gaussian NB Classifier

In [54]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [55]:
y_pred_nb = classifier_nb.predict(X_test)
print(np.concatenate((y_pred_nb.reshape(len(y_pred_nb),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [56]:
cm_nb = confusion_matrix(y_test, y_pred_nb)
print(cm_nb)
accuracy_score(y_test, y_pred_nb)

[[ 33  22]
 [ 12 450]]


0.9342359767891683

# Decision Tree

In [57]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 2)
classifier_dt.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=2, splitter='best')

In [58]:
y_pred_dt = classifier_dt.predict(X_test)
print(np.concatenate((y_pred_dt.reshape(len(y_pred_dt),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [0 1]]


In [59]:
cm_dt = confusion_matrix(y_test, y_pred_dt)
print(cm_dt)
accuracy_score(y_test, y_pred_dt)

[[ 38  17]
 [ 29 433]]


0.9110251450676983

# Random Forest

In [60]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 100, criterion ='gini',random_state=10)
classifier_rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=10, verbose=0,
                       warm_start=False)

In [61]:
y_pred_rf = classifier_rf.predict(X_test)
print(np.concatenate((y_pred_rf.reshape(len(y_pred_rf),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [0 1]]


In [62]:
cm_rf = confusion_matrix(y_test, y_pred_rf)
print(cm_rf)
accuracy_score(y_test, y_pred_rf)

[[ 31  24]
 [ 13 449]]


0.9284332688588007

# Nearest Centroid Classifier

In [63]:

from sklearn.neighbors import NearestCentroid
classifier_nc = NearestCentroid()
classifier_nc.fit(X_train,y_train)

NearestCentroid(metric='euclidean', shrink_threshold=None)

In [64]:
y_pred_nc = classifier_nc.predict(X_test)
print(np.concatenate((y_pred_nc.reshape(len(y_pred_nc),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [0 1]]


In [65]:
cm_nc = confusion_matrix(y_test, y_pred_nc)
print(cm_nc)
accuracy_score(y_test, y_pred_nc)

[[ 41  14]
 [127 335]]


0.7272727272727273